[tool.poetry]
name = "loggingframework"
version = "0.1.0"
description = ""
authors = ["Yan Rui Lim <YanRui.Lim@silabs.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^7.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
